subscription($receiverId: Int!, $teamId: Int!) {
  newDirectMessage(receiverId: $receiverId, teamId: $teamId) {
    id
    text
    receiverId
    teamId
    createdAt
    user {
      id
      username
    }
  }
}
