{
  me {
    id
    username
    teams {
      id
      name
      admin
      directMessagesMembers {
        id
        username
      }
      channels {
        id
        name
        teamId
      }
    }
  }
}
